platform :ios, '11.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  pod 'Firebase'
  
  pod 'GoogleMLKit/LanguageID', '2.3.0'
  pod 'GoogleMLKit/ImageLabelingCustom', '2.3.0'
  pod 'GoogleMLKit/BarcodeScanning', '2.3.0'
  pod 'GoogleMLKit/ImageLabeling', '2.3.0'
  pod 'GoogleMLKit/FaceDetection', '2.3.0'
  pod 'GoogleMLKit/PoseDetection', '2.3.0'
  pod 'GoogleMLKit/PoseDetectionAccurate', '2.3.0'
  pod 'GoogleMLKit/DigitalInkRecognition', '2.3.0'
  
  pod 'GoogleMLKit/TextRecognition', '2.3.0'
  pod 'GoogleMLKit/TextRecognitionChinese', '2.3.0'
  pod 'GoogleMLKit/TextRecognitionDevanagari', '2.3.0'
  pod 'GoogleMLKit/TextRecognitionJapanese', '2.3.0'
  pod 'GoogleMLKit/TextRecognitionKorean', '2.3.0'
end

# add this line:
$iOSVersion = '11.0'

post_install do |installer|
  # add these lines:
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=*]"] = "armv7"
    config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = $iOSVersion
  end

  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)

    # add these lines:
    target.build_configurations.each do |config|
      if Gem::Version.new($iOSVersion) > Gem::Version.new(config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'])
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = $iOSVersion
      end
    end

  end
end
